#!/bin/bash

source ./filecoin-common.sh

while true; do
    while true; do
		sectors=`$EXEC_LOTUS_STORAGE_MINER sectors list`
    	p1=`echo $sectors | grep "PreCommit1"`
		if [ "x" == "x$p1" ]; then break; fi
		sleep 5
	done

	for round in `seq 0 1`; do
		$EXEC_LOTUS_STORAGE_MINER sectors pledge
		if [ 0 != $? ]; then echo "Fail to pledge sectors"; exit 1; fi
    done

    while true; do
		sectors=`$EXEC_STORAGE_MINER sectors list`
    	p1=`echo $sectors | grep "PreCommit1"`
		if [ "x" != "x$p1" ]; then break; fi
		sleep 5
	done

	$EXEC_LOTUS_STORAGE_MINER info
done
