#!/bin/bash

source ./filecoin-common.sh
echo "Try to init storage miner for $ENV_SECTOR_SIZE at $LOTUS_STORAGE_PATH"
rm $LOTUS_STORAGE_PATH -rf

case $ENV_SECTOR_SIZE in
	512MiB)
		# $EXEC_LOTUS_STORAGE_MINER init --actor=t02029 --owner=t3qhvmmpjvjikceibgw22lq3guptgymyrf33yev5eoww2a7pcnoomph3m22obzcheedejxf4spg2b7yerk4hmq
		$EXEC_LOTUS_STORAGE_MINER init --actor=t02531 --owner=t3rdlykjv7ru3simnxx2yusdkmsgg6ay3kzlhotrlymnmjeghb53fmylefhlrcble6hwjipr7ft6krnbsbcyqa
		;;
	32GiB)
		$EXEC_LOTUS_STORAGE_MINER init --actor=t02044 --owner=t3rdlykjv7ru3simnxx2yusdkmsgg6ay3kzlhotrlymnmjeghb53fmylefhlrcble6hwjipr7ft6krnbsbcyqa
		;;
	*)
		echo "$ENV_SECTOR_SIZE is not supported"
		;;
esac
