#!/bin/bash

sudo apt-get install make
sudo apt-get install jq
sudo apt-get install curl

./rust-setup.sh
source $HOME/.cargo/env

echo "[source.crates-io]" > ~/.cargo/config
echo "registry = \"https://github.com/rust-lang/crates.io-index\"" >> ~/.cargo/config
echo "replace-with = 'sjtu'" >> ~/.cargo/config

echo "[source.sjtu]" >> ~/.cargo/config
echo "registry = \"https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index\"" >> ~/.cargo/config

rustup install nightly-2020-05-04

# sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt update
sudo apt install golang-go gcc git bzr jq pkg-config mesa-opencl-icd ocl-icd-opencl-dev
