#!/bin/bash

source ./filecoin-common.sh

if [ ! -d $ENV_LOTUS_ROOT ]; then
	$EXEC_LOTUS daemon &
	sleep 20
	killall -9 lotus
	sleep 20
fi

LOTUS_CONFIG=$ENV_LOTUS_ROOT/config.toml
sed -i "s/127.0.0.1/$ENV_MACH_IP/g" $LOTUS_CONFIG
sed -i "s/#  ListenAddress = \"/ListenAddress = \"/g" $LOTUS_CONFIG
sed -i "s/#  RemoteListenAddress = \"/RemoteListenAddress = \"$ENV_MACH_IP:1234/g" $LOTUS_CONFIG

##
## run 'lotus auth api-info --perm admin' to generate token
##
while true; do
	$EXEC_LOTUS daemon > $ENV_LOG_DIR/lotus.log 2>&1
	##
	## Let client to detect fail
	##
	sleep 60
done
